Repository Tinkoff/typed-schema, pull requests merged in 2020-05, with the labels that each got.

#320 Update swagger-ui-dist to 3.25.2
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#313 Update scalafmt-core to 2.5.1
  .scalafmt.conf
  examples/.scalafmt.conf
Labels: chore

#312 Update scalatags to 0.9.1
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#311 Update enumeratum-circe to 1.6.0
  project/Version.scala
Labels: chore

#310 Update enumeratum to 1.6.0
  project/Version.scala
Labels: chore

#309 Update akka-actor, akka-stream, ... to 2.6.5
  project/Version.scala
Labels: chore

#308 Update zio-interop-cats to 2.0.0.0-RC13
  project/Version.scala
Labels: chore

#325 Update tofu-env, tofu-optics-core, ... to 0.7.5
  project/Version.scala
Labels: chore

#324 Update derevo-cats to 0.11.3
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#323 Update akka-http, akka-http-testkit to 10.1.12
  project/Version.scala
Labels: chore

#322 Update scalatest to 3.1.2
  project/Version.scala
Labels: chore

#321 Update scalafmt-core to 2.5.2
  .scalafmt.conf
  examples/.scalafmt.conf
Labels: chore

#331 Update zio to 1.0.0-RC19-1
  project/Version.scala
Labels: chore

#329 Update swagger-ui-dist to 3.25.3
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#327 Update zio-interop-cats to 2.0.0.0-RC14
  project/Version.scala
Labels: chore

#328 Update enumeratum, enumeratum-circe to 1.6.1
  project/Version.scala
Labels: chore

#330 Add custom parameters and errors examples to the 'Getting started'
  modules/docs/src/main/tut/getting_started.md
Labels: chore

#333 Update zio to 1.0.0-RC19-2
  project/Version.scala
Labels: chore

#342 Update finagle-http to 20.5.0
  project/Version.scala
Labels: chore

#340 Update scalafmt-core to 2.5.3
  .scalafmt.conf
  examples/.scalafmt.conf
Labels: chore

#339 Update zio to 1.0.0-RC20
  project/Version.scala
Labels: chore

#337 Update swagger-ui-dist to 3.25.4
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#344 Update swagger-ui-dist to 3.25.5
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#345 Fix compile warnings
  .gitignore
  build.sbt
  modules/akkaHttp/src/test/scala/ru/tinkoff/tschema/akkaHttp/InnerSuite.scala
  modules/akkaHttp/src/test/scala/ru/tinkoff/tschema/akkaHttp/MultiParamSpec.scala
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/zioRouting/ReaderTRouting.scala
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/zioRouting/Routing.scala
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/zioRouting/package.scala
  modules/main/src/main/scala/ru/tinkoff/tschema/utils/json/CirceSupport.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerMapper.scala
Labels: chore, fix

#346 Require monad in finagle serve make
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/MkService.scala
Labels: fix
