Repository Tinkoff/typed-schema, pull requests merged in 2020-10, with the labels that each got.

#419 Update tofu-env, tofu-optics-core, ... to 0.8.0
  project/Version.scala
Labels: chore

#414 Update derevo-cats to 0.11.5
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#420 Update scalatags to 0.9.2
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#434 Update swagger-ui-dist to 3.35.1
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#433 Update akka-actor, akka-stream, ... to 2.6.10
  project/Version.scala
Labels: chore

#432 Update zio to 1.0.3
  project/Version.scala
Labels: chore

#429 Update sbt to 1.4.0
  examples/project/build.properties
  project/build.properties
Labels: chore

#428 Update zio-interop-cats to 2.1.4.1
  project/Version.scala
Labels: chore

#426 Update akka-http, akka-http-testkit to 10.2.1
  project/Version.scala
Labels: chore

#438 Update zio-interop-cats to 2.2.0.1
  project/Version.scala
Labels: chore

#436 Fix SwaggerMapper for FormField
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerMapper.scala
  modules/swagger/src/test/scala/ru/tinkoff/tschema/swagger/SwaggerMapperSpec.scala
Labels: fix

#437 Fix fiew non-exhaustive checks in the Macro
  modules/macros/src/main/scala/ru/tinkoff/tschema/macros/MakerMacro.scala
Labels: fix

#439 Fix deprecation warnings, added few functions for Swagger creation
  .scalafmt.conf
  modules/kernel/src/main/scala/ru/tinkoff/tschema/typeDSL.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/Swagger.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerFunctions.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerType.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerTypeable.scala
  modules/swagger/src/main/scala/ru/tinkoff/tschema/utils/json/Skippable.scala
Labels: enhancement, fix

#440 Update swagger-ui-dist to 3.35.2
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#442 Fix #364 and #389
  modules/akkaHttp/src/main/scala/ru/tinkoff/tschema/akkaHttp/Serve.scala
  modules/akkaHttp/src/test/scala/ru/tinkoff/tschema/akkaHttp/ResultSuite.scala
  modules/finagle-zio/src/test/scala/ru/tinkoff/tschema/finagle/zioRouting/ResultSuite.scala
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/Routed.scala
Labels: fix

#443 Update sbt to 1.4.1
  examples/project/build.properties
  project/build.properties
Labels: chore

#441 Update scalafmt-core to 2.7.5
  .scalafmt.conf
Labels: chore

#444 Update simulacrum to 1.0.1
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#445 Update Scala version in sbt and GH Workflows
  .github/workflows/scala.yml
  build.sbt
  project/Version.scala
Labels: chore

#447 Update sbt plugins, drop redundant sbt-dependency-graph
  examples/.scalafmt.conf
  examples/project/Version.scala
  examples/project/plugins.sbt
  project/plugins.sbt
Labels: chore
