Repository Tinkoff/typed-schema, pull requests merged in 2021-01, with the labels that each got.

#459 Update scalatest to 3.2.3
  project/Version.scala
Labels: chore

#476 Update cats-core, cats-effect, cats-free to 2.3.1
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#474 Update tofu-env, tofu-optics-core, ... to 0.9.0
  project/Version.scala
Labels: chore

#478 Update sbt to 1.4.6
  examples/project/build.properties
  project/build.properties
Labels: chore

#475 Update scalacheck to 1.15.2
  project/Version.scala
Labels: chore

#477 Update scala-collection-compat to 2.3.2
  build.sbt
Labels: chore

#480 Update derevo-cats to 0.11.6
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#481 Update akka-http-circe to 1.35.3
  project/Version.scala
Labels: chore

#483 Update swagger-ui-dist to 3.40.0
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#484 Update akka-actor, akka-stream, ... to 2.6.11
  project/Version.scala
Labels: chore

#485 Update akka-http, akka-http-testkit to 10.2.3
  project/Version.scala
Labels: chore

#486 Update zio to 1.0.4
  project/Version.scala
Labels: chore

#487 Add example field
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/OpenApi.scala
Labels: enhancement

#469 Fix unauthorized rejection.
  modules/finagle/src/main/scala/ru/tinkoff/tschema/finagle/Rejection.scala
Labels: bug

#490 Update Scala and GitHub CI dependencies version
  .github/workflows/release-drafter.yml
  .github/workflows/scala.yml
  .gitignore
  build.sbt
  examples/build.sbt
  project/Version.scala
Labels: chore

#489 Update scalatags to 0.9.3
  examples/project/Version.scala
  project/Version.scala
Labels: chore

#491 Update tethys-core, tethys-jackson to 0.20.0
  project/Version.scala
Labels: chore

#492 Update scala-collection-compat to 2.4.0
  build.sbt
Labels: chore

#488 Fix optional AsSingleOpenApiParam
  .gitignore
  modules/swagger/src/main/scala/ru/tinkoff/tschema/swagger/AsOpenApiParam.scala
  modules/swagger/src/test/scala/ru/tinkoff/tschema/swagger/MkSwaggerSpec.scala
Labels: bug

#493 Update akka-actor, akka-stream, ... to 2.6.12
  project/Version.scala
Labels: chore

#494 Update swagger-ui-dist to 3.41.1
  examples/project/Version.scala
  project/Version.scala
Labels: chore
